// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login.post').default>>>>
    }
    '/api/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logout.post').default>>>>
    }
    '/api/protected': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/protected.get').default>>>>
    }
    '/api/public': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public.get').default>>>>
    }
    '/api/session': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
  }
}
export {}